#!/bin/sh
#git push --no-verify
#./push.bash | xargs echo

#echo "$local_ref $local_sha $remote_ref $remote_sha";
remote="$1"
url="$2"

while read local_ref local_sha remote_ref remote_sha
do
  echo $local_sha > test-1
  echo $remote_sha > test-2
done

exit 1;